version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: ""
    GITHUB_REPOSITORY: "sleep-action"
    GITHUB_REPOSITORY_OWNER: "trilogy-group"
    RUNTIME_GITOPS_REPOSITORY: "runtime-gitops"
    ECR_REPOSITORY: "devflows/trilogy-group/sleep-action"
    IMAGE_TAG: "main-1f6f9e8"
    GITHUB_TOKEN: ""

phases:
  pre_build:
    commands:
      - echo Github Repository ${GITHUB_REPOSITORY}
      - echo ECR Repository ${ECR_REPOSITORY}
      - echo Image Tag ${IMAGE_TAG}

      - echo AWS_REGION ${AWS_REGION}
      - echo AWS_ACCOUNT_ID ${AWS_ACCOUNT_ID}

      - ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - echo ECR_REGISTRY ${ECR_REGISTRY}

      - export COMMIT_ID="${IMAGE_TAG##*-}"
      - echo COMMIT ID ${COMMIT_ID}
      
  build:
    commands:
      - echo Pulling Github Repository ${GITHUB_REPOSITORY}
      - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}.git
      
      - echo Checking out commit ID ${COMMIT_ID}
      - cd ${GITHUB_REPOSITORY} && git fetch --all && git checkout ${COMMIT_ID} && cd ..
      
      - echo Pulling Runtime Gitops Repository
      - git clone https://${GITHUB_TOKEN}@github.com/trilogy-group/${RUNTIME_GITOPS_REPOSITORY}.git

      - echo Logging in to Amazon ECR...
      - aws --region $AWS_REGION ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - echo Successfully logged in to ECR
      - bash build.sh

  post_build:
    commands:
      - docker logout ${ECR_REGISTRY}
