FROM python:3.7.5-slim
EXPOSE 8000
WORKDIR /code
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    build-essential \
    libffi-dev \
    libtool \
    automake \
    autoconf \
    cmake \
    git \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornH11Worker", "--bind", "0.0.0.0:8000", "main:app", "--timeout", "0"]