FROM python:3.6
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    build-essential \
    libffi-dev \
    libtool \
    automake \
    autoconf \
    cmake \
    git \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install Django==3.0
WORKDIR /code
COPY . /code
RUN pip install -r requirements.txt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]